version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: admin-mysql_db
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: BE_193237
      MYSQL_ROOT_PASSWORD: student
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pstudent" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - admin-mysql_default
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: admin-phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: admin-mysql_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - admin-mysql_default
    restart: unless-stopped

  prestashop:
    container_name: prestashop
    image: arivaldi/sklepik-prestashop:5.0
    platform: linux/amd64
    ports:
      - 19323:443
    entrypoint: [ "bash", "/entrypoint.sh" ]
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_193237
      DB_USER: root
      DB_PASSWD: student
      PS_LANGUAGE: ${PS_LANGUAGE:-pl}
      PS_COUNTRY: ${PS_COUNTRY:-pl}
      PS_DOMAIN: localhost:19323
      PS_FOLDER_ADMIN: admin
      PS_FOLDER_INSTALL: install
      PS_DEV_MODE: 1
      PS_INSTALL_AUTO: 1
      PS_ENABLE_SSL: 1
      ADMIN_MAIL: admin@admin.com
      ADMIN_PASSWD: admin
    networks:
      - admin-mysql_default
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    restart: unless-stopped

networks:
  admin-mysql_default:
